### ISSUE TITLE
pycharm warning of Unresolved reference

### ISSUE THREAD

**Issue by chris-tkinter** [patrick-kidger/torchtyping#23]
Hi, I really like this project! It's mind blowing for me!!

I have a question. When coding in pycharm using `TensorType` with a string dimension name, I got a warning about `unresolved reference`

![image](https://user-images.githubusercontent.com/86935669/124871699-32211d80-df79-11eb-9c0c-72a75d04e0c9.png)

I am not sure if this is a limitation of pycharm. I am using pycharm 2021.1.1, python 3.7.10 and torchtyping 0.1.4.

Thanks!

**Comment by patrick-kidger** [comment]
This is because strings in types are often used to denote forward references, e.g.
```python
def f(x: "A"): ...

class A: ...
```
As a result PyCharm is looking for an object called `batch` somewhere, and is complaining that it can't find it.

This is essentially a limitation of PyCharm -- it's assuming strings are being used in a way that they're only _sometimes_ used.

One option is to disable the warning, via whatever mechanism PyCharm offers for that. It's been a while since I've used PyCharm but I think you should be able to disable the warning locally, or for the whole file, or globally.

The other option is just to put `batch = None` anywhere in the file to fool PyCharm into thinking that something called `batch` exists.

**Comment by fzyzcjy** [comment]
Hi, is there any workarounds that does not require disabling linting or creating weird variables? thanks!
